340 Forbid teal_slices for excluded_varnames
insightsengineering/teal.slice pull request #393
Opened 2023-07-20 06:53 UTC by kartikeyakirar

this fixes: https://github.com/insightsengineering/teal.slice/issues/340

In PR, I have made updates to the logic of teal_slices by introducing an assertion to ensure that varnames are disjoint from excluded_varnames. Additionally, I have removed a similar check from set_filter_state since that condition will never be satisfied.

2023-07-20 11:49 UTC, chlebowa requested changes
Logic is shady but I will take a closer look when redundant conditions are removed.
Checks on `include_varnames` have not been implemented.

2023-07-20 11:49 UTC, chlebowa commented on R/teal_slices.R
You are manipulating values before assertions that ensure their proper type.

2023-07-20 11:49 UTC, chlebowa commented on R/teal_slices.R
> +  if (!is.null(excluded_datanames) && length(excluded_datanames) > 0) {
redundancy

2023-07-21 05:58 UTC, kartikeyakirar commented
Issue with Logic and Updated Changes:

The previous issue was that the logic was causing the creation of a duplicate name list. For example:
```
$mtcars
NULL
$mtcars
"cyl"
```
To address this problem, changes were made to iterate over the dataname from each slice element and extract the varname, while ignoring null values. An additional check for include_varname was introduced. This new check enforces that the filter for dataname should have varname from include_varname. However, this change resulted in some test failures for examples used in the package.

One specific test failure occurred when calling get_filter_state(datasets) on the dataset. The assertion failed with the following application code:
```
utils::data(miniACC, package = "MultiAssayExperiment")

datasets <- init_filtered_data(
  x = list(
    iris = list(dataset = iris),
    mae = list(dataset = miniACC)
  )
)
fs <- teal_slices(
  teal_slice(dataname = "iris", varname = "Species", selected = c("setosa", "versicolor")),
  teal_slice(dataname = "iris", varname = "Sepal.Length", selected = c(5.1, 6.4)),
  teal_slice(
    dataname = "mae", varname = "years_to_birth", selected = c(30, 50),
    keep_na = TRUE, keep_inf = FALSE
  ),
  teal_slice(
    dataname = "mae", varname = "vital_status", selected = "1",
    keep_na = FALSE
  ),
  teal_slice(
    dataname = "mae", varname = "gender", selected = "female",
    keep_na = TRUE
  ),
  teal_slice(
    dataname = "mae", varname = "ARRAY_TYPE", selected = "",
    keep_na = TRUE, experiment = "RPPAArray", arg = "subset"
  )
)

# set initial filter state
set_filter_state(datasets, filter = fs)

# get filter state
get_filter_state(datasets)
```
The error message received was:
```
Error in FUN(X[[i]], ...) :
Assertion on 'varnames[[name]]' failed: Must be a subset of {'patientID','years_to_birth','vital_status','days_to_death','days_to_last_followup','tumor_tissue_site','pathologic_stage','pathology_T_stage','pathology_N_stage','gender','date_of_initial_pathologic_diagnosis','radiation_therapy','histological_type','residual_tumor','number_of_lymph_nodes','race','ethnicity','Histology','C1A.C1B','mRNA_K4','MethyLevel','miRNA.cluster','SCNA.cluster','protein.cluster','COC','OncoSign','purity','ploidy','genome_doublings','ADS'}, but has additional elements {'ARRAY_TYPE'}.

```
Upon investigation, it was found that the "ARRAY_TYPE" variable does not exist in the miniACC dataset. Previously, before assertion, this would get filtered out at set_filter_state(), but currently, it fails assertion if teal_slice does not contain the varname defined in include_varname for a particular dataname.

The approach taken to remove the teal_slice containing the "ARRAY_TYPE" varname from the example to pass the tests seems appropriate. However, it's worth noting that the example containing "ARRAY_TYPE" might have served a specific purpose, and without sufficient understanding of miniACC, it's difficult to determine if its removal is entirely appropriate.

I wanted to confirm if this is correct approach for assertion or what should be expected behavior in above scenarios?

2023-07-21 06:05 UTC, chlebowa commented
> Upon investigation, it was found that the "ARRAY_TYPE" variable does not exist in the miniACC dataset. Previously, before assertion, this would get filtered out at set_filter_state(), but currently, it fails assertion if teal_slice does not contain the varname defined in include_varname for a particular dataname.
> 
> The approach taken to remove the teal_slice containing the "ARRAY_TYPE" varname from the example to pass the tests seems appropriate. However, it's worth noting that the example containing "ARRAY_TYPE" might have served a specific purpose, and without sufficient understanding of miniACC, it's difficult to determine if its removal is entirely appropriate.
> 
> I wanted to confirm if this is correct approach for assertion or what should be expected behavior in above scenarios?

Wrong.
```
library(MultiAssayExperiment)
data(miniACC)
ex <- miniACC[["RPPAArray"]]
names(rowData(ex))
```

2023-07-21 07:10 UTC, kartikeyakirar commented
Oh, I was accessing it incorrectly. working on logic again,

2023-07-21 11:47 UTC, kartikeyakirar commented
"ARRAY_TYPE" from miniACC data is filtered out and which also causing the test to fail . logging bug https://github.com/insightsengineering/teal.slice/issues/399

2023-07-21 15:35 UTC, chlebowa commented
Blocked by #400.

2023-07-24 08:48 UTC, kartikeyakirar commented
As per discussion with @gogonzo,
Both` include_varnames` and` exclude_varnames `are currently considered "experimental." We should defer the decision on how to effectively communicate the variables to be included or excluded until later. Consequently, the asserts in `teal_slices` should not be a significant concern at this time.

2023-07-24 08:48 UTC, closed without merging