#467 change factors to characters for selected and choices at teal_slice creation
insightsengineering/teal.slice pull request #469
Opened 2023-09-28 11:01 UTC by m7pr

Alternative for #468 that closes #467 as a consequence of #373

We changed the behavior of `teal_slice` that converts `factors` to `characters` for the unified result of `store/restore`.

```r
> slices_path <- withr::local_file("slices.json")
> tss <- teal_slices(
+   teal_slice(
+     dataname = "ADSL",
+     varname = "EOSDTM",
+     choices = factor(c("a", "b", "c")),
+     selected = factor(c("a", "b"))
+   )
+ )
> 
> slices_store(tss, slices_path)
> tss_restored <- slices_restore(slices_path)
> 
> class(shiny::isolate(tss_restored[[1]]$selected))
[1] "character"
> class(shiny::isolate(tss_restored[[1]]$choices))
[1] "character"
> class(shiny::isolate(tss[[1]]$selected))
[1] "character"
> class(shiny::isolate(tss[[1]]$choices))
[1] "character"
```

2023-09-28 13:30 UTC, chlebowa requested changes

2023-09-28 13:30 UTC, chlebowa commented on R/teal_slice.R
> +#' Type and size depends on variable type. If specified as `factor`, it is converted to `character`.
```suggestion
#' Type and size depends on variable type. Factors are coerced to character.
```

2023-09-28 13:30 UTC, chlebowa commented on tests/testthat/test-teal_slice-store.R
> +  "teal_slice store/restore restores factors as characters in selected and choices because they are converted",
I think this is better tested on `teal_slice`, that's where the conversion takes place.

2023-09-28 14:08 UTC, m7pr commented on R/teal_slice.R
> +#' Type and size depends on variable type. If specified as `factor`, it is converted to `character`.
3678fbdb6f061054b1707d89d7c4e6cf13fe74af

2023-09-28 14:20 UTC, chlebowa approved these changes
Cool :ok_hand: 
One last thing, would you please prefix all `testthat` function calls?

2023-09-28 14:20 UTC, chlebowa commented on tests/testthat/test-teal_slice-store.R
> +  expect_identical(class(shiny::isolate(tss_restored[[1]]$choices)), "character")
`expect_s3_class`?

2023-09-29 08:05 UTC, m7pr commented on tests/testthat/test-teal_slice-store.R
> +  expect_identical(class(shiny::isolate(tss_restored[[1]]$choices)), "character")
@chlebowa suprisingly didn't work lol

```r
expect_s3_class(shiny::isolate(tss_restored[[1]]$selected), "character")
#> Error: shiny::isolate(tss_restored[[1]]$selected) is not an S3 object
```

2023-09-29 08:07 UTC, chlebowa commented on tests/testthat/test-teal_slice-store.R
> +  expect_identical(class(shiny::isolate(tss_restored[[1]]$choices)), "character")
say what? :monocle_face:

2023-09-29 08:10 UTC, m7pr commented on tests/testthat/test-teal_slice-store.R
> +  expect_identical(class(shiny::isolate(tss_restored[[1]]$choices)), "character")
Even below doesnt work

```r
tss_restored_list <- shiny::isolate(shiny::reactiveValuesToList(tss_restored[[1]]))
expect_s3_class(tss_restored_list$selected, "character")
#> Error: tss_restored_list$selected is not an S3 object
```

weeeird

```r
tss_restored_list$selected
[1] "a" "b"
```

2023-09-29 08:11 UTC, m7pr commented
Testthat prefixed!

2023-09-29 08:13 UTC, chlebowa commented on tests/testthat/test-teal_slice-store.R
> +  expect_identical(class(shiny::isolate(tss_restored[[1]]$choices)), "character")
All righty then.
`expect_type((shiny::isolate(tss_restored[[1]]$selected)), "character")`

2023-09-29 09:40 UTC, merged