1033 dro psupport for list filter
insightsengineering/teal.slice pull request #517
Opened 2024-01-11 10:14 UTC by chlebowa

part of https://github.com/insightsengineering/teal/issues/1033
companion to https://github.com/insightsengineering/teal/pull/1040

2024-01-11 11:39 UTC, gogonzo approved these changes

2024-01-15 12:50 UTC, pawelru requested changes
Please correct the docs accordingly:

https://github.com/insightsengineering/teal.slice/blob/ea691771d192535bbacfa76117576e63a3332df0/R/FilteredDatasetMAE.R#L63-L67
https://github.com/insightsengineering/teal.slice/blob/ea691771d192535bbacfa76117576e63a3332df0/R/FilterStates.R#L247-L250

2024-01-15 13:34 UTC, pawelru commented
Sorry - my previous comment was unrelated - it was about docs for `teal_slices` and not `teal_slice`

2024-01-15 13:59 UTC, pawelru approved these changes

2024-01-15 14:53 UTC, merged