adding internal example
insightsengineering/teal.slice pull request #521
Opened 2024-01-12 12:52 UTC by kartikeyakirar

part of https://github.com/insightsengineering/teal.slice/pull/506
- https://github.com/insightsengineering/nestdevs-tasks/issues/48

this PR add backs internal examples using `getFromNamespace()`

2024-01-12 13:54 UTC, averissimo commented on R/FilterStateDatettime.R
> +#' filter_state <- teal.slice:::DatetimeFilterState$new(
```suggestion
#' filter_state <- DatetimeFilterState$new(
```

2024-01-12 14:00 UTC, chlebowa requested changes
Just a few tweaks.

2024-01-12 14:00 UTC, chlebowa commented on R/FilterState-utils.R
> +#' shiny::isolate(filter_state$get_call())
Since we don't prefix `shinyApp` and `shiny` is attached anyway, let's remove this as well.
```suggestion
#' isolate(filter_state$get_call())
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilterStateDatettime.R
> +#' filter_state <- teal.slice:::DatetimeFilterState$new(
```suggestion
#' filter_state <- DatetimeFilterState$new(
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilterStates-utils.R
> +#' library(shiny)
```suggestion
```

Not required as `shiny` is 1) attached, 2) imported.

2024-01-12 14:00 UTC, chlebowa commented on R/FilterStatesDF.R
> +#' library(shiny)
```suggestion
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilteredData-utils.R
> +#' library(shiny)
```suggestion
#' library(shinyjs)
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilteredData-utils.R
> +#'   shinyjs::useShinyjs(),
```suggestion
#'   useShinyjs(),
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilteredData-utils.R
> +#'                  shinyjs::hide("content")
```suggestion
#'                  hide("content")
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilteredData-utils.R
> +#'                  shinyjs::show("content")
```suggestion
#'                  show("content")
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilteredData-utils.R
> +#'                  shinyjs::toggle("content")
```suggestion
#'                  toggle("content")
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilteredDatasetDataframe.R
> +#' library(shiny)
```suggestion
```

2024-01-12 14:00 UTC, chlebowa commented on R/FilteredDatasetDefault.R
> +#' library(shiny)
```suggestion
```

2024-01-12 14:00 UTC, chlebowa commented on R/utils.R
> +#' # [1] 1
```suggestion
#' make_c_call(1:3)
#' make_c_call(1)
```

2024-01-12 14:03 UTC, averissimo reviewed
All examples seem to run locally. I'm assuming they are unchanged from previous versions other than the triple colon mod.

Minor corrections to documentation (`@example` to `@examples` and one leftover tripe colon)

2024-01-12 14:04 UTC, averissimo commented on R/FilterStateDatettime.R
> +#' filter_state <- teal.slice:::DatetimeFilterState$new(
Nevermind about this as @chlebowa also mentioned on his review. Address there.

2024-01-12 15:17 UTC, chlebowa commented on R/FilteredData.R
> +#' @example
can't believe I missed it :facepalm:

2024-01-12 15:18 UTC, chlebowa commented on R/FilteredData.R
> +#' @example
`@example` if for pointing to examples stored in a separate file

2024-01-12 15:24 UTC, kartikeyakirar commented
> I'm assuming they are unchanged from previous versions 

two examples are changed as they were not working and throwing errors. few minor tweaks were done..

2024-01-12 15:36 UTC, averissimo commented on R/FilteredData.R
> +#' @example
Thanks for the extra context, looking back I can see that the screenshot alone wasn't enough.

@chlebowa you and @kartikeyakirar have been a monster team making changes and reviewing the pre-release activities!

2024-01-12 15:39 UTC, chlebowa commented on R/FilteredData.R
> +#' @example
> the screenshot alone wasn't enough

Fortunately I banged my head on this particular wall once already :wink:

2024-01-15 08:14 UTC, kartikeyakirar commented on R/FilteredDatasetMAE.R
>  #' @title `MAEFilteredDataset` `R6` class
done

2024-01-15 09:11 UTC, chlebowa approved these changes
:+1:

2024-01-15 09:13 UTC, merged