Fix rounding for pretty formatting of sliderInput steps
insightsengineering/teal.slice pull request #98
Opened 2022-09-19 22:18 UTC by asbates

# Pull Request

Fixes #41. 

This PR implements nicer displayed numbers for slider inputs. It uses essentially the [same method as Shiny](https://github.com/rstudio/shiny/blob/c21ba0baca5a3eeaeabbdbcb8e9e83a6bd9a0bb9/R/input-slider.R#L255-L274).

2022-09-21 22:26 UTC, donyunardi approved these changes

2022-09-21 23:01 UTC, donyunardi commented
Maybe we should investigate if we could just pass the ranges directly to `optionalSliderInput` and remove `min`, `max`, and `step` argument to optimize our code.

I'll make a new issue so we can look into this.

2022-09-22 07:07 UTC, Polkas requested changes
Please add the NEWS record and add tests
I will check the code in the moment

2022-09-22 07:17 UTC, Polkas commented on R/FilterState.R
> +      min <- min(v_pretty_range)
Think about a separate private method/utils function which could be properly tested and the code more clear. Even linked shiny use such `findStepSize`.

2022-09-22 07:19 UTC, Polkas commented on R/FilterState.R
> +      # essentially the same as shiny's implementation
if you think the solution is "essentially the same", then you have to leave a proper reference.

2022-09-27 22:24 UTC, asbates commented
> Maybe we should investigate if we could just pass the ranges directly to `optionalSliderInput` and remove `min`, `max`, and `step` arguments to optimize our code.
> 
> https://github.com/insightsengineering/teal.slice/blob/a449203ab5267fd208fe68d606a89ead1cc9be6a/R/FilterState.R#L1381-L1403
> 
> I'll make a new issue so we can look into this.

This seems like the easiest solution to me. I would also add that we may not need the separate issue. Is there a particular reason why we have `FilterState$get_pretty_range_inputs`? If not, then instead of making the current proposed fix and then coming back and undoing it later (#101), why not forgo the custom method? It would be simpler both in terms of code and administrative overhead to make the 'correct' change now.

2022-09-28 08:23 UTC, mhallal1 commented
> > Maybe we should investigate if we could just pass the ranges directly to `optionalSliderInput` and remove `min`, `max`, and `step` arguments to optimize our code.
> > https://github.com/insightsengineering/teal.slice/blob/a449203ab5267fd208fe68d606a89ead1cc9be6a/R/FilterState.R#L1381-L1403
> > 
> > I'll make a new issue so we can look into this.
> 
> This seems like the easiest solution to me. I would also add that we may not need the separate issue. Is there a particular reason why we have `FilterState$get_pretty_range_inputs`? If not, then instead of making the current proposed fix and then coming back and undoing it later (#101), why not forgo the custom method? It would be simpler both in terms of code and administrative overhead to make the 'correct' change now.
> 
> @mhallal1 What do you think? Should we pass the values directly to `optionalSliderInput` (therefore `shiny::sliderInput`) and let Shiny handle the formatting?

@asbates I like the proposed solution here, I would respond to Maciej's comments on citing the original work (add the link in the code) and adding some tests if possible.
Regarding the comment above, as we are doing an agile setup, we can fix this task and close it and investigate the need (or not) of `FilterState$get_pretty_range_inputs` in another issue. This is to keep track of what is done in the required time space so we do not take much more time for an issue assigned less time/complexity.

2022-09-29 06:04 UTC, mhallal1 approved these changes
LGTM

2022-09-29 21:57 UTC, merged